// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFOan4S0HkPJc53Py2eHTl_ceIEPiuqaw',
    appId: '1:968960363332:web:6b12bbe23921c505b52511',
    messagingSenderId: '968960363332',
    projectId: 'flutter1-c46a8',
    authDomain: 'flutter1-c46a8.firebaseapp.com',
    storageBucket: 'flutter1-c46a8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8PWCaR1A7UTh_HLr5vtbgq3q-EOS9pk0',
    appId: '1:968960363332:android:c7ba4ee74d0abc0cb52511',
    messagingSenderId: '968960363332',
    projectId: 'flutter1-c46a8',
    storageBucket: 'flutter1-c46a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOpAkUSkwBwi_zKxpB0thPuGxrxK0E2e4',
    appId: '1:968960363332:ios:3349cc0dea220f16b52511',
    messagingSenderId: '968960363332',
    projectId: 'flutter1-c46a8',
    storageBucket: 'flutter1-c46a8.appspot.com',
    iosBundleId: 'com.example.actividadApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOpAkUSkwBwi_zKxpB0thPuGxrxK0E2e4',
    appId: '1:968960363332:ios:3349cc0dea220f16b52511',
    messagingSenderId: '968960363332',
    projectId: 'flutter1-c46a8',
    storageBucket: 'flutter1-c46a8.appspot.com',
    iosBundleId: 'com.example.actividadApi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFOan4S0HkPJc53Py2eHTl_ceIEPiuqaw',
    appId: '1:968960363332:web:3f1a92d44d083b01b52511',
    messagingSenderId: '968960363332',
    projectId: 'flutter1-c46a8',
    authDomain: 'flutter1-c46a8.firebaseapp.com',
    storageBucket: 'flutter1-c46a8.appspot.com',
  );
}
